name: VendingMachines
main: org.devathon.contest2016.VendingMachines
version: 1.0
commands:
 createVendingMachine:
  usage: /<command>
  description: Command to create vending machines.
  permission: VendingMachines.create